In [1]:
import numpy as np
import pandas as pd
import tables_io

In [2]:
PHOTOM_lePhare_small = tables_io.read("/pscratch/sd/s/sajkov/analysis_pipeline/runs/smallLePhareSet_07Jul26/PHOTOMETRY_DeepField_noisy_lpReference_smallLePhareSet_07Jul26.pq")
PHOTOM_lePhare_big   = tables_io.read("/pscratch/sd/s/sajkov/analysis_pipeline/runs/07Jul26/PHOTOMETRY_DeepField_noisy_lpReference_07Jul26.pq")

column_list None
column_list None

In [13]:
REDSHIFTS_lePhare_small = np.load("/pscratch/sd/s/sajkov/analysis_pipeline/runs/smallLePhareSet_07Jul26/TRUEREDSHIFTS_DeepField_lpReference.npy")
REDSHIFTS_lePhare_big   = np.load("/pscratch/sd/s/sajkov/analysis_pipeline/runs/07Jul26/TRUEREDSHIFTS_DeepField_lpReference.npy")
REDSHIFTS_deepField = np.load("/pscratch/sd/s/sajkov/analysis_pipeline/runs/07Jul26/TRUEREDSHIFTS_DeepField.npy")
PHOTOZS_deepField_lePhare = tables_io.read("/pscratch/sd/s/sajkov/analysis_pipeline/runs/07Jul26/PHOTOZS_DeepField_lePhare_07Jul26.pq")["photo-z"]

column_list None

In [16]:
REDSHIFTS_deepField

array([0.9499769 , 5.2313423 , 0.02873397, ..., 1.3036196 , 2.9985065 ,
       2.8448644 ], shape=(10000,), dtype=float32)

In [15]:
PHOTOZS_deepField_lePhare

0       0.923949
1       5.224156
2       0.010039
3       0.221483
4       0.669962
          ...
9995    0.930466
9996    1.462460
9997    1.200000
9998    2.917132
9999    2.563790
Name: photo-z, Length: 10000, dtype: float64

In [8]:
np.shape(REDSHIFTS_lePhare_big)

(10000,)

In [3]:
PHOTOM_lePhare_big

,LSST_u,LSST_u_err,LSST_g,LSST_g_err,LSST_r,LSST_r_err,LSST_i,LSST_i_err,LSST_z,LSST_z_err,...,HSC_MB_11,HSC_MB_11_err,HSC_MB_12,HSC_MB_12_err,HSC_MB_13,HSC_MB_13_err,HSC_MB_14,HSC_MB_14_err,HSC_MB_15,HSC_MB_15_err
index,,,,,,,,,,,,,,,,,,,,,
136251,25.755294,0.034701,25.722531,0.014878,25.610362,0.011741,25.461142,0.009954,25.251973,0.014398,...,25.548880,0.202867,25.756715,0.229516,25.476507,0.205890,24.948767,0.166959,25.585022,0.377638
1259537,28.666202,0.417841,27.884637,0.098898,27.148917,0.043489,26.029918,0.015339,25.489128,0.017505,...,26.013405,0.297391,25.822520,0.242361,25.703935,0.248717,25.345541,0.233127,24.444529,0.147550
1083960,25.758995,0.034815,25.234566,0.010259,25.280860,0.009307,25.263554,0.008749,25.236545,0.014221,...,25.216123,0.152920,25.373525,0.166214,25.559820,0.220738,25.168528,0.201110,25.330886,0.308956
460895,24.968174,0.017491,24.157074,0.006005,23.018181,0.005095,22.486287,0.005031,22.312584,0.005081,...,22.550226,0.014851,22.444601,0.013014,22.343704,0.013526,22.235410,0.015535,21.926814,0.016208
1460280,27.297324,0.135683,26.122270,0.020807,25.753570,0.013105,25.626695,0.011199,25.428825,0.016644,...,25.659254,0.222480,25.692086,0.217499,25.354355,0.185758,25.471129,0.258545,25.754123,0.430098
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1072520,25.495780,0.027583,25.300377,0.010749,24.876486,0.007369,24.394398,0.005951,23.858496,0.006252,...,24.459052,0.078942,24.026806,0.050963,23.943955,0.054106,23.762766,0.059085,23.768847,0.081770
1173921,25.990368,0.042776,25.803931,0.015904,25.319457,0.009548,25.030435,0.007653,25.258719,0.014477,...,24.491141,0.081215,25.431023,0.174557,25.126890,0.153020,25.372894,0.238464,25.987651,0.512132
1091973,25.841296,0.037458,24.867817,0.008118,24.728988,0.006880,24.665501,0.006493,24.608726,0.009000,...,24.599356,0.089358,24.751289,0.096890,24.630785,0.099434,24.688345,0.133473,24.537156,0.159756
1895711,24.942536,0.017119,23.760546,0.005507,22.433836,0.005033,21.253877,0.005003,20.591613,0.005003,...,21.108651,0.006232,20.876420,0.005752,20.625268,0.005631,20.434421,0.005736,20.330903,0.006138
727224,24.448293,0.011549,24.272068,0.006219,24.183300,0.005760,24.004367,0.005485,23.916135,0.006377,...,23.910779,0.048480,23.894401,0.045289,23.872147,0.050752,23.809051,0.061570,23.861242,0.088721

In [4]:
PHOTOM_lePhare_small

,LSST_u,LSST_u_err,LSST_g,LSST_g_err,LSST_r,LSST_r_err,LSST_i,LSST_i_err,LSST_z,LSST_z_err,...,HSC_MB_11,HSC_MB_11_err,HSC_MB_12,HSC_MB_12_err,HSC_MB_13,HSC_MB_13_err,HSC_MB_14,HSC_MB_14_err,HSC_MB_15,HSC_MB_15_err
index,,,,,,,,,,,,,,,,,,,,,
136251,25.755294,0.034701,25.722531,0.014878,25.610362,0.011741,25.461142,0.009954,25.251973,0.014398,...,25.548880,0.202867,25.756715,0.229516,25.476507,0.205890,24.948767,0.166959,25.585022,0.377638
1259537,28.666202,0.417841,27.884637,0.098898,27.148917,0.043489,26.029918,0.015339,25.489128,0.017505,...,26.013405,0.297391,25.822520,0.242361,25.703935,0.248717,25.345541,0.233127,24.444529,0.147550
1083960,25.758995,0.034815,25.234566,0.010259,25.280860,0.009307,25.263554,0.008749,25.236545,0.014221,...,25.216123,0.152920,25.373525,0.166214,25.559820,0.220738,25.168528,0.201110,25.330886,0.308956
460895,24.968174,0.017491,24.157074,0.006005,23.018181,0.005095,22.486287,0.005031,22.312584,0.005081,...,22.550226,0.014851,22.444601,0.013014,22.343704,0.013526,22.235410,0.015535,21.926814,0.016208
1460280,27.297324,0.135683,26.122270,0.020807,25.753570,0.013105,25.626695,0.011199,25.428825,0.016644,...,25.659254,0.222480,25.692086,0.217499,25.354355,0.185758,25.471129,0.258545,25.754123,0.430098
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990415,25.430463,0.026044,25.165522,0.009782,24.963833,0.007708,24.557139,0.006249,25.169957,0.013486,...,23.744573,0.041804,25.119887,0.133652,25.005622,0.137846,25.416562,0.247212,25.648404,0.396642
1375716,27.328424,0.139379,26.738642,0.035745,25.852315,0.014172,25.484627,0.010117,25.354952,0.015657,...,25.268262,0.159908,25.613299,0.203621,25.527346,0.214839,24.842674,0.152467,24.928792,0.222394
729621,27.234965,0.128549,27.271512,0.057463,26.999375,0.038066,26.654542,0.026138,26.426892,0.039710,...,26.453055,0.420035,inf,inf,26.479344,0.458713,25.985101,0.389565,26.374336,0.674097
1049791,23.957302,0.008306,23.936448,0.005689,23.807200,0.005394,23.443686,0.005178,23.268978,0.005455,...,23.220412,0.026273,23.311838,0.027008,23.304269,0.030623,23.128780,0.033594,23.223142,0.050346
536600,26.634516,0.075889,26.662756,0.033415,26.658985,0.028152,26.516116,0.023160,26.428695,0.039774,...,26.079523,0.313600,inf,inf,26.866220,0.608094,26.480811,0.564139,25.964996,0.503669

In [3]:
## 5-sigma limiting depths ------------------
### LSST: median values for COSMOS deep field from https://usdf-maf.slac.stanford.edu/summaryStats?runId=5#Basics_Coadd%20M5
### Roman from https://github.com/jfcrenshaw/photerr/blob/a014b39729ddde3daf80be2dbe82f5a7f958882c/photerr/roman.py#L120-L126
### HSC Niji (60 min exposure) from https://sites.google.com/view/hsc-mb-survey3/filter-specification?authuser=0 
###
### Acessed June 3, 2026
### --------------------------------------------

M5_DEPTHS_DeepField = {'LSST_u'    : 27.74,
                      'LSST_g'    : 28.69,
                      'LSST_r'    : 28.88,
                      'LSST_i'    : 28.96,
                      'LSST_z'    : 28.26,
                      'LSST_y'    : 26.63,
                      'Roman_F062': 27.7,
                      'Roman_F087': 27.7,
                      'Roman_F106': 27.6,
                      'Roman_F129': 27.5,
                      'Roman_F158': 27.0,
                      'Roman_F184': 25.9,
                      'Roman_F213': 28.3,
                      'HSC_MB_00' : 26.41,
                      'HSC_MB_01' : 26.51,
                      'HSC_MB_02' : 26.45,
                      'HSC_MB_03' : 26.69,
                      'HSC_MB_04' : 26.93,
                      'HSC_MB_05' : 26.62,
                      'HSC_MB_06' : 26.26,
                      'HSC_MB_07' : 26.02,
                      'HSC_MB_08' : 26.07,
                      'HSC_MB_09' : 26.00,
                      'HSC_MB_10' : 26.06,
                      'HSC_MB_11' : 25.52,
                      'HSC_MB_12' : 25.58,
                      'HSC_MB_13' : 25.43,
                      'HSC_MB_14' : 25.15,
                      'HSC_MB_15' : 24.79}


### 5-sigma limiting depths for WideFastDeep from https://usdf-maf.slac.stanford.edu/summaryStats?runId=5#Basics_Coadd%20M5
### Column `DD:WFD CoaddM5`
M5_DEPTHS_WideFastDeep = {'LSST_u'    : 25.61,
                          'LSST_g'    : 26.90,
                          'LSST_r'    : 26.87,
                          'LSST_i'    : 26.43,
                          'LSST_z'    : 25.73,
                          'LSST_y'    : 24.79}

### Get list of bands
BANDS_DeepField = list(M5_DEPTHS_DeepField.keys())
ERR_BANDS_DeepField = [f"{key}_err" for key in BANDS_DeepField]

BANDS_WideFastDeep = list(M5_DEPTHS_WideFastDeep.keys())
ERR_BANDS_WideFastDeep = [f"{key}_err" for key in BANDS_WideFastDeep]

In [28]:
## Prepare input data
TRAINING_DATA_UMAP = tables_io.read("/pscratch/sd/s/sajkov/analysis_pipeline/runs/06Jul26_11kDataPoints/PHOTOMETRY_DeepField_noisy_06Jul26.pq")

TRAINING_PHOTOMETRY_UMAP = TRAINING_DATA_UMAP[BANDS_WideFastDeep]
TRAINING_PHOTOMERRS_UMAP = TRAINING_DATA_UMAP[ERR_BANDS_WideFastDeep]

TRAINING_REDSHIFTS_UMAP_specZs  = np.load("/pscratch/sd/s/sajkov/analysis_pipeline/runs/06Jul26_11kDataPoints/TRUEREDSHIFTS_DeepField.pkl.npy")
TRAINING_REDSHIFTS_UMAP_photoZs = tables_io.read("/pscratch/sd/s/sajkov/analysis_pipeline/runs/06Jul26_11kDataPoints/PHOTOZS_DeepField_lePhare_06Jul26.pq")

ESTIMATION_DATA_UMAP = tables_io.read("/pscratch/sd/s/sajkov/analysis_pipeline/runs/06Jul26_11kDataPoints/PHOTOMETRY_WideFastDeep_noisy_06Jul26.pq")

ESTIMATION_PHOTOMETRY_UMAP = ESTIMATION_DATA_UMAP[BANDS_WideFastDeep]
ESTIMATION_PHOTOMERRS_UMAP = ESTIMATION_DATA_UMAP[ERR_BANDS_WideFastDeep]

column_list None
column_list None
column_list None

In [29]:
COLORNAMES_WideFastDeep = [f"{BANDS_WideFastDeep[i].split('_')[-1]}-{BANDS_WideFastDeep[i + 1].split('_')[-1]}"
                           for i in range(len(BANDS_WideFastDeep) - 1)]

COLERRNAMES_WideFastDeep = [f"{BANDS_WideFastDeep[i].split('_')[-1]}-{BANDS_WideFastDeep[i + 1].split('_')[-1]}_err"
                           for i in range(len(BANDS_WideFastDeep) - 1)]

In [47]:
COLORS_WideFastDeep = pd.DataFrame(
    {COLORNAMES_WideFastDeep[i]:
        TRAINING_PHOTOMETRY_UMAP[BANDS_WideFastDeep[i]] - TRAINING_PHOTOMETRY_UMAP[BANDS_WideFastDeep[i + 1]]
            for i in range(len(BANDS_WideFastDeep) - 1)}
)

# COLERRS_WideFastDeep = pd.DataFrame(
#     {COLERRNAMES_WideFastDeep[i]:
#         TRAINING_PHOTOMERRS_UMAP[ERR_BANDS_WideFastDeep[i]] - TRAINING_PHOTOMERRS_UMAP[ERR_BANDS_WideFastDeep[i + 1]]
#             for i in range(len(ERR_BANDS_WideFastDeep) - 1)}
# )

COLERRS_WideFastDeep = pd.DataFrame(
    {COLERRNAMES_WideFastDeep[i]:
        np.clip(np.sqrt(TRAINING_PHOTOMERRS_UMAP[ERR_BANDS_WideFastDeep[i]]**2 + TRAINING_PHOTOMERRS_UMAP[ERR_BANDS_WideFastDeep[i + 1]]**2),
                None, 0.05)
            for i in range(len(ERR_BANDS_WideFastDeep) - 1)}
)

In [40]:
TRAINING_PHOTOMETRY_UMAP

            LSST_u     LSST_g     LSST_r     LSST_i     LSST_z     LSST_y
index
232136   26.074474  26.139794  26.039279  25.495192  25.809098  25.241489
1184099  29.242006  29.423577  28.832412  26.593863  25.712719  25.517956
1373785  25.302653  24.198437  23.728439  23.506351  23.385119  23.284056
1767073  27.138766  26.436428  26.018765  25.906271  25.858277  25.910881
566949   24.247786  23.970521  23.360148  22.874242  22.713242  22.628279
...            ...        ...        ...        ...        ...        ...
1155869  28.957846  28.637337  26.698958  26.328271  26.320241  26.196137
419882   25.887895  25.445968  25.063193  24.554449  24.221012  23.757473
894501   29.220125  28.595875  27.978868  28.023723  27.782204  27.332550
356125   24.513004  24.505477  24.402698  24.064822  23.937888  24.115371
1014254  29.281281  29.074886  28.587685  28.289074  27.731207  26.448912

[999 rows x 6 columns]

In [48]:
TRAINING_PHOTOMERRS_UMAP

,LSST_u_err,LSST_g_err,LSST_r_err,LSST_i_err,LSST_z_err,LSST_y_err
index,,,,,,
232136,0.047011,0.021322,0.016635,0.010239,0.023255,0.060462
1184099,0.529180,0.369643,0.200539,0.025057,0.021377,0.077730
1373785,0.023533,0.006095,0.005356,0.005212,0.005572,0.011151
1767073,0.123281,0.027686,0.016352,0.013967,0.024282,0.110901
566949,0.010045,0.005746,0.005189,0.005075,0.005180,0.007401
...,...,...,...,...,...,...
1155869,0.484063,0.199670,0.029536,0.019869,0.036681,0.143123
419882,0.039702,0.012035,0.008173,0.006262,0.007266,0.016199
894501,0.526717,0.192690,0.094104,0.091158,0.137644,0.361922
356125,0.012192,0.006804,0.006121,0.005553,0.006446,0.021993
1014254,0.533113,0.286288,0.162177,0.115811,0.131529,0.178729

In [53]:
np.isnan(COLORS_WideFastDeep).sum()

u-g    0
g-r    0
r-i    0
i-z    0
z-y    0
dtype: int64

In [54]:
np.isnan(COLERRS_WideFastDeep).sum()

u-g_err    0
g-r_err    0
r-i_err    0
i-z_err    0
z-y_err    0
dtype: int64

In [9]:
COLORS_WideFastDeep

['u-g', 'g-r', 'r-i', 'i-z', 'z-y']

In [7]:
TRAINING_PHOTOMETRY_UMAP_MAGNITUDES

            LSST_u     LSST_g     LSST_r     LSST_i     LSST_z     LSST_y
index
232136   26.074474  26.139794  26.039279  25.495192  25.809098  25.241489
1184099  29.242006  29.423577  28.832412  26.593863  25.712719  25.517956
1373785  25.302653  24.198437  23.728439  23.506351  23.385119  23.284056
1767073  27.138766  26.436428  26.018765  25.906271  25.858277  25.910881
566949   24.247786  23.970521  23.360148  22.874242  22.713242  22.628279
...            ...        ...        ...        ...        ...        ...
1155869  28.957846  28.637337  26.698958  26.328271  26.320241  26.196137
419882   25.887895  25.445968  25.063193  24.554449  24.221012  23.757473
894501   29.220125  28.595875  27.978868  28.023723  27.782204  27.332550
356125   24.513004  24.505477  24.402698  24.064822  23.937888  24.115371
1014254  29.281281  29.074886  28.587685  28.289074  27.731207  26.448912

[999 rows x 6 columns]